# Generated by Django 4.2.4 on 2023-08-17 23:31

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dados_pagamento',
            name='bandeira',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='fk_bandeira', to='users.bandeiras_cartoes'),
        ),
        migrations.AlterField(
            model_name='dados_pagamento',
            name='usuario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fk_dados_pagamento_usuario', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='enderecos',
            name='geral',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='fk_endereco_geral', to='users.enderecos_geral'),
        ),
        migrations.AlterField(
            model_name='telefones',
            name='cod_pais',
            field=models.ForeignKey(default='55', on_delete=django.db.models.deletion.PROTECT, related_name='fk_cod_pais', to='users.cod_paises'),
        ),
        migrations.AlterField(
            model_name='usuarios',
            name='celular',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='fk_celular', to='users.telefones'),
        ),
        migrations.AlterField(
            model_name='usuarios',
            name='endereco',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='fk_endereco_usuario', to='users.enderecos'),
        ),
        migrations.AlterField(
            model_name='usuarios',
            name='orientacao_sexual',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='fk_orientacao_sexual', to='users.orientacao_sexual'),
        ),
        migrations.AlterField(
            model_name='usuarios',
            name='whatsapp',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='fk_whatsapp', to='users.telefones'),
        ),
    ]
