# Generated by Django 4.2.4 on 2023-08-17 23:12

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('app', '0001_initial'),
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='vendas',
            name='dados_pagamento',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='users.dados_pagamento', verbose_name='fk_dados_pag'),
        ),
        migrations.AddField(
            model_name='vendas',
            name='ingresso',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='app.ingressos', verbose_name='fk_ingresso'),
        ),
        migrations.AddField(
            model_name='vendas',
            name='usuario',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='fk_usuario'),
        ),
        migrations.AddField(
            model_name='ingressos_x_interessados',
            name='ingresso',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.ingressos', verbose_name='fk_ingresso'),
        ),
        migrations.AddField(
            model_name='ingressos_x_interessados',
            name='tipo_interessado',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='app.tipos_interessados', verbose_name='fk_tipo_interessado'),
        ),
        migrations.AddField(
            model_name='ingressos',
            name='evento',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.eventos', verbose_name='fk_evento'),
        ),
        migrations.AddField(
            model_name='eventos',
            name='categoria',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='app.categorias', verbose_name='fk_categoria'),
        ),
        migrations.AddField(
            model_name='eventos',
            name='dono_evento',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='fk_dono'),
        ),
        migrations.AddField(
            model_name='eventos',
            name='endereco',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='users.enderecos', verbose_name='fk_endereco'),
        ),
    ]
