# Generated by Django 4.2.4 on 2023-08-17 23:31

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_alter_dados_pagamento_bandeira_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('app', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='eventos',
            name='categoria',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='fk_categoria', to='app.categorias'),
        ),
        migrations.AlterField(
            model_name='eventos',
            name='dono_evento',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='fk_dono', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='eventos',
            name='endereco',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='fk_endereco_evento', to='users.enderecos'),
        ),
        migrations.AlterField(
            model_name='ingressos',
            name='evento',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fk_evento', to='app.eventos'),
        ),
        migrations.AlterField(
            model_name='ingressos',
            name='quantidade',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='ingressos',
            name='quantidade_maxima_por_venda',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='ingressos',
            name='quantidade_minima_por_venda',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='ingressos_x_interessados',
            name='ingresso',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fk_ingresso_interessado', to='app.ingressos'),
        ),
        migrations.AlterField(
            model_name='ingressos_x_interessados',
            name='tipo_interessado',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='fk_tipo_interessado', to='app.tipos_interessados'),
        ),
        migrations.AlterField(
            model_name='vendas',
            name='dados_pagamento',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='fk_dados_pag', to='users.dados_pagamento'),
        ),
        migrations.AlterField(
            model_name='vendas',
            name='ingresso',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='fk_ingresso', to='app.ingressos'),
        ),
        migrations.AlterField(
            model_name='vendas',
            name='usuario',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='fk_venda_usuario', to=settings.AUTH_USER_MODEL),
        ),
    ]
